# Generated by Django 4.2.4 on 2023-08-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='test',
            new_name='text',
        ),
    ]
